system:
  ip_forward: true
  masquerade:
    saddr: "10.0.1.1/24"
relays:
  #------------------------
  - ingress:
      type: tun
      name: tun10
      cidr: "10.0.0.2/24"
      peer: "10.0.0.1"
    egress:
      type: udp
      dial: "localhost:4000"
      password: "pass"
  #------------------------
  - ingress:
      type: udp
      listen: "localhost:4000"
      peers:
        - password: "pass"
          saddr: "10.0.0.2"
    middlewares:
      - type: nat
        src_range_start: "10.0.1.10"
        src_range_end: "10.0.1.250"
        src_range_start_darwin: "10.0.1.1"
        src_range_end_darwin: "10.0.1.1"
    egress:
      type: tun
      name: tun11
      cidr: "10.0.1.2/24"
      peer: "10.0.1.1"
